In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [4]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.full((2,2),9)

array([[9, 9],
       [9, 9]])

In [9]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [11]:
np.arange(1,101,9)

array([  1,  10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100])

In [17]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr.shape)

(4, 3)


In [21]:
print("the total element" , arr.size)
print("the dimension is",arr.ndim)
print("the datatype is",arr.dtype)

the total element 12
the dimension is 2
the datatype is int64


In [22]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype='float32')
print(arr)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
