In [5]:
import random
import numpy as np
num = random.randint(1,20)
arr = np.full((3,3),num)
print(arr)
print(arr.shape)

[[3 3 3]
 [3 3 3]
 [3 3 3]]
(3, 3)


In [7]:
import numpy as np
floats = np.array([1.1, 2.2, 3.3])
ints = floats.astype(int)
print(ints)

[1 2 3]


In [8]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
even = arr % 2 == 0
print(arr[even])

[2 4 6 8]


In [9]:
import numpy as np
arr = np.arange(1,10)
mat = arr.reshape(3,3)
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
