In [12]:
import numpy as np
arr = np.array([[1,2,3,5],[4,5,6,7],[7,8,9,10],[38,2,421,32]])
print(arr)

[[  1   2   3   5]
 [  4   5   6   7]
 [  7   8   9  10]
 [ 38   2 421  32]]


In [13]:
np.sum(arr,axis=0)

array([ 50,  17, 439,  54])

In [14]:
np.sum(arr,axis=1)

array([ 11,  22,  34, 493])

In [20]:
arr[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [22]:
import numpy as np
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
print(arr3D)
 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [23]:
print(arr3D.shape)

(2, 2, 3)


In [24]:
print(arr3D[0, 1, 2]) 

6
